### ISSUE TITLE
VACANCIES.md is outdated.

### ISSUE THREAD

**Issue by zarthon** [Financial-Times/careers#33]
https://ft.wd3.myworkdayjobs.com/en-US/FT_External_Careers/job/OSB-London-35-hours/Senior-Engineer_JR002452 doesn't exist anymore.

**Comment by sjparkinson** [comment]
Thanks for the heads up @zarthon. I've just given the file an update.

You can also see all our open positions at https://ft.wd3.myworkdayjobs.com/en-US/FT_External_Careers.
